### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#111]
The build of the `develop` branch of this project currently appears to be broken, as of today an `mvn clean` causes:

`[ERROR] Failed to resolve target definition /home/vorburger/dev/github/m2e-code-quality/m2e-code-quality/neon/neon.target: Could not find "net.sf.eclipsecs.feature.group/7.6.0.201703111252" in the repositories of the current location -> [Help 1]`

and a `mvn -Dtarget.platform=oxygen clean` causes:

`[ERROR] Failed to resolve target definition /home/vorburger/dev/github/m2e-code-quality/m2e-code-quality/oxygen/oxygen.target: Could not find "org.eclipse.jdt.feature.group/3.13.0.v20170308-2105" in the repositories of the current location -> [Help 1]`

however a `mvn -Dtarget.platform=mars clean` does work...

**Comment by ArloL** [comment]
Hi @vorburger,

thanks for letting me know. I have fixed the build:

https://travis-ci.org/m2e-code-quality/m2e-code-quality

The problem was that the update sites stopped serving these specific versions of the features. I have solved it by exploring those repositories and finding the currently available versions and setting them in the *.target files.
