### ISSUE TITLE
Plugin does not pick up maven-checkstyle-plugin in the POM "reporting" section

### ISSUE THREAD

**Issue by michael-schnell** [m2e-code-quality/m2e-code-quality#118]
Hi there,

I normally configure the Checkstyle plugin within the "reporting" section of Maven:

```xml
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <configLocation>${checkstyle.config.location}</configLocation>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

```
It seems that this does not get picked up by the plugin (no Eclipse config is generated).

Moving it to the "build" section seems to work.

Is this by intention or am I missing something?

Cheers,
Michael

**Comment by vorburger** [comment]
@michael-schnell I'm not really sure here, and would welcome input from others (e.g. @victornoel @erwint @ctron ...), but  from what I understand, I think this may be "normal" - aren't Maven plugins in `<reporting>` section used only to ... well, produce reports? If that's the case, then.. there's "nothing to do" for this project here to configure M2E, no? 

When you use Maven plugins like Checkstyle's in `<reporting>` in a POM, then don't you ALSO have (to have) them in `<build>` ? Then it should all work, no? Or do I misunderstand this and one can have e.g. Checkstyle only in `<reporting>` but not in `<build>` and it still runs, and checks style (same as if it's only in `<build>`), and additionally produces reports? I don't remember it like this, but it's been years since I last used `<reporting>` on a project.

Let's close this issue in 1 month from today if no further updates; hope that's fair.

**Comment by ctron** [comment]
Sorry, I don't know that myself. But I would assume you are right, I never saw any M2E plugin interact with the reporting section.

**Comment by michael-schnell** [comment]
@vorburger As the project description states "This project provides Eclipse plugins that bridge the Maven and Eclipse plugins for Checkstyle ..." - So if there is a checkstyle configuration in the Maven POM, I'd expect the m2e-code-quality plugin to create an Eclipse checkstyle config. No matter if "build" or "report" section. Both options should be supported.  

The "report" way is even the first option that is described on the Maven Plugin page itself: https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html 

The doc states: "If you want to report to the console or fail the build, you must add an execution of checkstyle::check to the <build> element" and "To generate the Checkstyle report as part of the Project Reports, add the Checkstyle Plugin in the <reporting> section".
