### ISSUE TITLE
The composite update site refers to non existent repositories

### ISSUE THREAD

**Issue by jan-z** [m2e-code-quality/m2e-code-quality#344]
When installing the plugin from the documented update site (https://m2e-code-quality.github.io/m2e-code-quality-p2-site/) several non existant repositories get added on the first check for updates.

The error in the update process looks like this:

> Some sites could not be found.  See the error log for more detail.
> No repository found at https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/.
> No repository found at http://download.eclipse.org/technology/m2e/releases.
> Unable to read repository at http://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site.
> No repository found at https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/.
> No repository found at http://eclipse-cs.sourceforge.net/update.
> No repository found at http://eclipse-cs.sf.net/update.

This does not happen when the plugin is installed using a versioned update site like https://m2e-code-quality.github.io/m2e-code-quality-p2-site/2.1.0/

Unfortunately I do not know to fix this.

**Comment by famod** [comment]
Same here (with 2.1.0)! [Has been like that for a very long time.](https://github.com/m2e-code-quality/m2e-code-quality/issues/251#issuecomment-961268726)

> This does not happen when the plugin is installed using a versioned update site like https://m2e-code-quality.github.io/m2e-code-quality-p2-site/2.1.0/

Interesting!
My workaround is/was to disable (not remove!) all affected sites and restart eclipse. After that, check for updates should finish just fine.

**Comment by adangel** [comment]
I think, the cause is, that https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ is a composite repository, which also contains all the old versions: https://github.com/m2e-code-quality/m2e-code-quality-p2-site/blob/gh-pages/compositeContent.xml

And the old versions reference the old update sites, e.g. https://github.com/m2e-code-quality/m2e-code-quality/blob/gh-pages/site/1.0.0.201501120825/associate-sites.xml

For a new release, the following update sites are referenced:
https://github.com/m2e-code-quality/m2e-code-quality/blob/9d78571bd5221976636f124a7acb8b4680715ecd/pom.xml#L33-L36

These should be correct and still working.

So, one solution would be to move the old versions away into a separate "archive" (or so) repository. Then these are still available if needed, but not by default. And these non-existent repository should not be referenced anymore.
