### ISSUE TITLE
Checkstyle version mismatch between Eclipse and Maven

### ISSUE THREAD

**Issue by anton-johansson** [m2e-code-quality/m2e-code-quality#99]
This issue isn't really related to this project, I just have a question regarding this set up. We have Checkstyle in our parent POM, which runs various checks. We use m2e-code-quality to transfer the configs from the POM to Eclipse Checkstyle Plugin. However, we have no way of enforcing that Eclipse Checkstyle Plugin uses the same version of Checkstyle as the Maven plugin does, which mean developers might get different warnings in Eclipse than in Maven.

Is this something that anyone has thought about? Is there a smart solution to this? It would be cool if the Checkstyle plugin (hence why this issue is probably misplaced) could be configured with a specific version of checkstyle at runtime, which m2e-code-quality could pass in.

**Comment by ArloL** [comment]
How about a custom checkstyle rule that takes a minimum version as a value and that triggers an ERROR if the current version is too low?

You would have to get it merged upstream though since adding custom checkstyle rules to Eclipse is pretty complicated w/o something like oomph / Eclipse Installer in place. Not a solution for *right now* but could prevent issues in future.

**Comment by anton-johansson** [comment]
Hmm, a rule that checks the version of the currently running Checkstyle. I like that! I would require it to be mroe strict and checking an exact version (one developer had a newer version, which gave us a new error).

However, when I think about it, it's strange that the developer got a new error, since our config is static... Maybe better to look into that. :P

Closing for now!

Thanks!
